#ifndef _NET_CPSW_STATS_
#define _NET_CPSW_STATS_

#include <stdio.h>
#include <net/cpsw.h>

#define CPSW_STATS_GOOD_RX_FRAMES	(CPSW_STATS + 0x00)
#define CPSW_STATS_BROADCAST_RX_FRAMES	(CPSW_STATS + 0x04)
#define CPSW_STATS_MULTICAST_RX_FRAMES	(CPSW_STATS + 0x08)
#define CPSW_STATS_PAUSE_RX_FRAMES	(CPSW_STATS + 0x0c)
#define CPSW_STATS_RX_CRC_ERR_FRAMES	(CPSW_STATS + 0x10)
#define CPSW_STATS_RX_ALIGN_ERR_FRAMES	(CPSW_STATS + 0x14)
#define CPSW_STATS_OVERSIZE_RX_FRAMES	(CPSW_STATS + 0x18)
#define CPSW_STATS_RX_JABBERS_FRAMES	(CPSW_STATS + 0x1c)
#define CPSW_STATS_SHORT_RX_FRAMES	(CPSW_STATS + 0x20)
#define CPSW_STATS_RX_OCTETS_FRAMES	(CPSW_STATS + 0x24)
#define CPSW_STATS_RX_SOF_OR_FRAMES	(CPSW_STATS + 0x84)
#define CPSW_STATS_RX_MOF_OR_FRAMES	(CPSW_STATS + 0x88)
#define CPSW_STATS_RX_DMA_OR_FRAMES	(CPSW_STATS + 0x8c)

static void cpsw_stats_rx(void)
{
	printf("CPSW_STATS_GOOD_RX_FRAMES = %08x\n", readl(CPSW_STATS_GOOD_RX_FRAMES));
	printf("CPSW_STATS_BROADCAST_RX_FRAMES = %08x\n", readl(CPSW_STATS_BROADCAST_RX_FRAMES));
	printf("CPSW_STATS_MULTICAST_RX_FRAMES = %08x\n", readl(CPSW_STATS_MULTICAST_RX_FRAMES));
	printf("CPSW_STATS_PAUSE_RX_FRAMES = %08x\n", readl(CPSW_STATS_PAUSE_RX_FRAMES));
	printf("CPSW_STATS_RX_CRC_ERR_FRAMES = %08x\n", readl(CPSW_STATS_RX_CRC_ERR_FRAMES));
	printf("CPSW_STATS_RX_ALIGN_ERR_FRAMES = %08x\n", readl(CPSW_STATS_RX_ALIGN_ERR_FRAMES));
	printf("CPSW_STATS_OVERSIZE_RX_FRAMES = %08x\n", readl(CPSW_STATS_OVERSIZE_RX_FRAMES));
	printf("CPSW_STATS_RX_JABBERS_FRAMES = %08x\n", readl(CPSW_STATS_RX_JABBERS_FRAMES));
	printf("CPSW_STATS_SHORT_RX_FRAMES = %08x\n", readl(CPSW_STATS_SHORT_RX_FRAMES));
	printf("CPSW_STATS_RX_OCTETS_FRAMES = %08x\n", readl(CPSW_STATS_RX_OCTETS_FRAMES));
	printf("CPSW_STATS_RX_SOF_OR_FRAMES = %08x\n", readl(CPSW_STATS_RX_SOF_OR_FRAMES));
	printf("CPSW_STATS_RX_MOF_OR_FRAMES = %08x\n", readl(CPSW_STATS_RX_MOF_OR_FRAMES));
	printf("CPSW_STATS_RX_DMA_OR_FRAMES = %08x\n", readl(CPSW_STATS_RX_DMA_OR_FRAMES));
}

#endif /* _NET_CPSW_STATS_ */
