#ifndef _NET_CPSW_STATS_
#define _NET_CPSW_STATS_

#include <stdio.h>
#include <net/cpsw.h>

#define CPSW_STATS_GOOD_RX_FRAMES	(CPSW_STATS + 0x00)
#define CPSW_STATS_BROADCAST_RX_FRAMES	(CPSW_STATS + 0x04)
#define CPSW_STATS_MULTICAST_RX_FRAMES	(CPSW_STATS + 0x08)
#define CPSW_STATS_PAUSE_RX_FRAMES	(CPSW_STATS + 0x0c)
#define CPSW_STATS_RX_CRC_ERR_FRAMES	(CPSW_STATS + 0x10)
#define CPSW_STATS_RX_ALIGN_ERR_FRAMES	(CPSW_STATS + 0x14)
#define CPSW_STATS_OVERSIZE_RX_FRAMES	(CPSW_STATS + 0x18)
#define CPSW_STATS_RX_JABBERS_FRAMES	(CPSW_STATS + 0x1c)
#define CPSW_STATS_SHORT_RX_FRAMES	(CPSW_STATS + 0x20)
#define CPSW_STATS_RX_OCTETS_FRAMES	(CPSW_STATS + 0x24)
#define CPSW_STATS_RX_SOF_OR_FRAMES	(CPSW_STATS + 0x84)
#define CPSW_STATS_RX_MOF_OR_FRAMES	(CPSW_STATS + 0x88)
#define CPSW_STATS_RX_DMA_OR_FRAMES	(CPSW_STATS + 0x8c)

#define CPSW_STATS_GOOD_TX_FRAMES	(CPSW_STATS + 0x34)
#define CPSW_STATS_BROADCAST_TX_FRAMES	(CPSW_STATS + 0x38)
#define CPSW_STATS_MULTICAST_TX_FRAMES	(CPSW_STATS + 0x3c)
#define CPSW_STATS_PAUSE_TX_FRAMES	(CPSW_STATS + 0x40)
#define CPSW_STATS_DEFERRED_TX_FRAMES	(CPSW_STATS + 0x44)
#define CPSW_STATS_COLLISIONS_FRAMES	(CPSW_STATS + 0x48)
#define CPSW_STATS_SINGLE_COLLISIONS_TX_FRAMES	(CPSW_STATS + 0x4c)
#define CPSW_STATS_MULTIPLE_COLLISIONS_TX_FRAMES	(CPSW_STATS + 0x50)
#define CPSW_STATS_EXCESSIVE_COLLISIONS_TX_FRAMES	(CPSW_STATS + 0x54)
#define CPSW_STATS_LATE_COLLISIONS_TX_FRAMES	(CPSW_STATS + 0x58)
#define CPSW_STATS_TX_UNDERRUN_FRAMES	(CPSW_STATS + 0x5c)
#define CPSW_STATS_CARRIER_SENSE_ERR_FRAMES	(CPSW_STATS + 0x60)
#define CPSW_STATS_TX_OCTETS_FRAMES	(CPSW_STATS + 0x64)

static void cpsw_stats_rx(void)
{
	printf("CPSW_STATS_GOOD_RX_FRAMES = %08x\n", readl(CPSW_STATS_GOOD_RX_FRAMES));
	printf("CPSW_STATS_BROADCAST_RX_FRAMES = %08x\n", readl(CPSW_STATS_BROADCAST_RX_FRAMES));
	printf("CPSW_STATS_MULTICAST_RX_FRAMES = %08x\n", readl(CPSW_STATS_MULTICAST_RX_FRAMES));
	printf("CPSW_STATS_PAUSE_RX_FRAMES = %08x\n", readl(CPSW_STATS_PAUSE_RX_FRAMES));
	printf("CPSW_STATS_RX_CRC_ERR_FRAMES = %08x\n", readl(CPSW_STATS_RX_CRC_ERR_FRAMES));
	printf("CPSW_STATS_RX_ALIGN_ERR_FRAMES = %08x\n", readl(CPSW_STATS_RX_ALIGN_ERR_FRAMES));
	printf("CPSW_STATS_OVERSIZE_RX_FRAMES = %08x\n", readl(CPSW_STATS_OVERSIZE_RX_FRAMES));
	printf("CPSW_STATS_RX_JABBERS_FRAMES = %08x\n", readl(CPSW_STATS_RX_JABBERS_FRAMES));
	printf("CPSW_STATS_SHORT_RX_FRAMES = %08x\n", readl(CPSW_STATS_SHORT_RX_FRAMES));
	printf("CPSW_STATS_RX_OCTETS_FRAMES = %08x\n", readl(CPSW_STATS_RX_OCTETS_FRAMES));
	printf("CPSW_STATS_RX_SOF_OR_FRAMES = %08x\n", readl(CPSW_STATS_RX_SOF_OR_FRAMES));
	printf("CPSW_STATS_RX_MOF_OR_FRAMES = %08x\n", readl(CPSW_STATS_RX_MOF_OR_FRAMES));
	printf("CPSW_STATS_RX_DMA_OR_FRAMES = %08x\n", readl(CPSW_STATS_RX_DMA_OR_FRAMES));
}

static void cpsw_stats_tx(void)
{
	printf("CPSW_STATS_GOOD_TX_FRAMES = %08x\n", readl(CPSW_STATS_GOOD_TX_FRAMES));
	printf("CPSW_STATS_BROADCAST_TX_FRAMES = %08x\n", readl(CPSW_STATS_BROADCAST_TX_FRAMES));
	printf("CPSW_STATS_MULTICAST_TX_FRAMES = %08x\n", readl(CPSW_STATS_MULTICAST_TX_FRAMES));
	printf("CPSW_STATS_PAUSE_TX_FRAMES = %08x\n", readl(CPSW_STATS_PAUSE_TX_FRAMES));
	printf("CPSW_STATS_DEFERRED_TX_FRAMES = %08x\n", readl(CPSW_STATS_DEFERRED_TX_FRAMES));
	printf("CPSW_STATS_COLLISIONS_FRAMES = %08x\n", readl(CPSW_STATS_COLLISIONS_FRAMES));
	printf("CPSW_STATS_SINGLE_COLLISIONS_TX_FRAMES = %08x\n", readl(CPSW_STATS_SINGLE_COLLISIONS_TX_FRAMES));
	printf("CPSW_STATS_MULTIPLE_COLLISIONS_TX_FRAMES = %08x\n", readl(CPSW_STATS_MULTIPLE_COLLISIONS_TX_FRAMES));
	printf("CPSW_STATS_EXCESSIVE_COLLISIONS_TX_FRAMES = %08x\n", readl(CPSW_STATS_EXCESSIVE_COLLISIONS_TX_FRAMES));
	printf("CPSW_STATS_LATE_COLLISIONS_TX_FRAMES = %08x\n", readl(CPSW_STATS_LATE_COLLISIONS_TX_FRAMES));
	printf("CPSW_STATS_TX_UNDERRUN_FRAMES = %08x\n", readl(CPSW_STATS_TX_UNDERRUN_FRAMES));
	printf("CPSW_STATS_CARRIER_SENSE_ERR_FRAMES = %08x\n", readl(CPSW_STATS_CARRIER_SENSE_ERR_FRAMES));
	printf("CPSW_STATS_TX_OCTETS_FRAMES = %08x\n", readl(CPSW_STATS_TX_OCTETS_FRAMES));
}

#endif /* _NET_CPSW_STATS_ */
