#ifndef _NET_CPSW_H
#define _NET_CPSW_H

#define CPSW_WR 0x4A101200
#define CPSW_ALE 0x4A100D00
#define CPSW_SS 0x4A100000
#define CPSW_PORT 0x4A100100
#define CPSW_CPDMA 0x4A100800
#define CPSW_STATS 0x4A100900
#define CPSW_STATERAM 0x4A100A00
#define CPSW_CPTS 0x4A100C00
#define CPSW_SL1 0x4A100D80
#define CPSW_SL2 0x4A100DC0
#define CPSW_MDIO 0x4A101000

/* CPSW_MDIO */
#define CPSW_MDIO_CONTROL	(CPSW_MDIO + 0x4)

/* CPSW_MDIO_CONTROL */
#define CPSW_MDIO_CONTROL_ENABLE_BIT	(30)

/* CPSW_SL1 */
#define CPSW_SL1_SOFT_RESET	(CPSW_SL1 + 0x0c)
#define CPSW_SL1_RX_MAXLEN	(CPSW_SL1 + 0x10)
#define CPSW_SL1_MACCONTROL	(CPSW_SL1 + 0x04)

/* CPSW_SL1_MACCONTROL */
#define CPSW_SL1_MACCONTROL_FULLDUPLEX_BIT	(0)
#define CPSW_SL1_MACCONTROL_GMII_EN_BIT	(5)
#define CPSW_SL1_MACCONTROL_IFCTL_A_BIT	(15)

/* CPSW_SS */
#define CPSW_SS_SOFT_RESET	(CPSW_SS + 0x8)
#define CPSW_SS_STAT_PORT_EN	(CPSW_SS + 0xc)

/* CPSW_MDIO_STAT_PORT_EN */
#define CPSW_SS_STAT_PORT_EN_P0_STAT_EN_BIT	(0)
#define CPSW_SS_STAT_PORT_EN_P1_STAT_EN_BIT	(1)
#define CPSW_SS_STAT_PORT_EN_P2_STAT_EN_BIT	(2)

/* CPSW_CPDMA */
#define CPSW_CPDMA_SOFT_RESET	(CPSW_CPDMA + 0x1c)
#define CPSW_CPDMA_TX_CONTROL	(CPSW_CPDMA + 0x04)
#define CPSW_CPDMA_RX_CONTROL	(CPSW_CPDMA + 0x14)
#define CPSW_CPDMA_DMASTATUS	(CPSW_CPDMA + 0x24)

/* CPSW_CPDMA_TX_CONTROL */
#define CPSW_CPDMA_TX_CONTROL_TX_EN_BIT	(0)
#define CPSW_CPDMA_RX_CONTROL_RX_EN_BIT	(0)

/* CPSW_CPDMA_DMASTATUS */
#define CPSW_CPDMA_RX_HOST_ERR_0000	"No Err"
#define CPSW_CPDMA_RX_HOST_ERR_0001	"Reserved"
#define CPSW_CPDMA_RX_HOST_ERR_0010	"Ownership bit not set in input buffer"
#define CPSW_CPDMA_RX_HOST_ERR_0011	"Reserved"
#define CPSW_CPDMA_RX_HOST_ERR_0100	"Zero BUffer Pointer"
#define CPSW_CPDMA_RX_HOST_ERR_0101	"Zero buffer length on non-SOP descriptor"
#define CPSW_CPDMA_RX_HOST_ERR_0110	"SOP buffer length not greater than offset"
#define CPSW_CPDMA_RX_HOST_ERR_1111	"Reserved"

#define CPSW_CPDMA_DMASTATUS_IDLE	(1 << 31)

/* CPSW_ALE */
#define CPSW_ALE_CONTROL	(CPSW_ALE + 0x08)
#define CPSW_ALE_PORTCTL0	(CPSW_ALE + 0x40)
#define CPSW_ALE_PORTCTL1	(CPSW_ALE + 0x44)

/* CPSW_ALE CONTROL*/
#define CPSW_ALE_CONTROL_ALE_ENABLE_BIT	(31)
#define CPSW_ALE_CONTROL_ALE_TABLE_CLEAR_BIT	(30)

/* CPSW_ALE_PORTCTL */
#define CPSW_ALE_PORTCTL_PORT_STATE_FORWARD	(3)

/* CPSW_PORT */
#define CPSW_PORT_P0_CPDMA_TX_PRI_MAP	(CPSW_PORT + 0x1c)
#define CPSW_PORT_P0_CPDMA_RX_CH_MAP	(CPSW_PORT + 0x20)
#define CPSW_PORT_P1_SA_LO		(CPSW_PORT + 0x120)
#define CPSW_PORT_P1_SA_HI		(CPSW_PORT + 0x124)

/* CPSW_STATERAM */
#define CPSW_STATERAM_TX0_HDP	(CPSW_STATERAM + 0X00)
#define CPSW_STATERAM_TX1_HDP	(CPSW_STATERAM + 0X04)
#define CPSW_STATERAM_TX2_HDP	(CPSW_STATERAM + 0X08)
#define CPSW_STATERAM_TX3_HDP	(CPSW_STATERAM + 0X0c)
#define CPSW_STATERAM_TX4_HDP	(CPSW_STATERAM + 0X10)
#define CPSW_STATERAM_TX5_HDP	(CPSW_STATERAM + 0X14)
#define CPSW_STATERAM_TX6_HDP	(CPSW_STATERAM + 0X18)
#define CPSW_STATERAM_TX7_HDP	(CPSW_STATERAM + 0X1c)
#define CPSW_STATERAM_RX0_HDP	(CPSW_STATERAM + 0X20)
#define CPSW_STATERAM_RX1_HDP	(CPSW_STATERAM + 0X24)
#define CPSW_STATERAM_RX2_HDP	(CPSW_STATERAM + 0X28)
#define CPSW_STATERAM_RX3_HDP	(CPSW_STATERAM + 0X2c)
#define CPSW_STATERAM_RX4_HDP	(CPSW_STATERAM + 0X30)
#define CPSW_STATERAM_RX5_HDP	(CPSW_STATERAM + 0X34)
#define CPSW_STATERAM_RX6_HDP	(CPSW_STATERAM + 0X38)
#define CPSW_STATERAM_RX7_HDP	(CPSW_STATERAM + 0X3c)
#define CPSW_STATERAM_TX0_CP	(CPSW_STATERAM + 0X40)
#define CPSW_STATERAM_TX1_CP	(CPSW_STATERAM + 0X44)
#define CPSW_STATERAM_TX2_CP	(CPSW_STATERAM + 0X48)
#define CPSW_STATERAM_TX3_CP	(CPSW_STATERAM + 0X4c)
#define CPSW_STATERAM_TX4_CP	(CPSW_STATERAM + 0X50)
#define CPSW_STATERAM_TX5_CP	(CPSW_STATERAM + 0X54)
#define CPSW_STATERAM_TX6_CP	(CPSW_STATERAM + 0X58)
#define CPSW_STATERAM_TX7_CP	(CPSW_STATERAM + 0X5c)
#define CPSW_STATERAM_RX0_CP	(CPSW_STATERAM + 0X60)
#define CPSW_STATERAM_RX1_CP	(CPSW_STATERAM + 0X64)
#define CPSW_STATERAM_RX2_CP	(CPSW_STATERAM + 0X68)
#define CPSW_STATERAM_RX3_CP	(CPSW_STATERAM + 0X6c)
#define CPSW_STATERAM_RX4_CP	(CPSW_STATERAM + 0X70)
#define CPSW_STATERAM_RX5_CP	(CPSW_STATERAM + 0X74)
#define CPSW_STATERAM_RX6_CP	(CPSW_STATERAM + 0X78)
#define CPSW_STATERAM_RX7_CP	(CPSW_STATERAM + 0X7c)

#define CPSW_CPPI_RAM	0x4A102000

#define CPSW_RX_MAX_PKT_LEN	0x5ee

#define CPSW_DESC_OWNERSHIP_DMA	(1 << 29)
#define CPSW_DESC_OWNERSHIP_PORT	(0 << 29)
#define CPSW_DESC_SOP	(1 << 31)
#define CPSW_DESC_EOP	(1 << 30)
#define CPSW_DESC_PKT_LEN_MASK	(0x7ff)

#endif /* _NET_CPSW_H */
